---
title: "Tarea2_ASIES_LUIS-PUICON"
output: html_notebook
---
Grafica_1
```{r}
sf::st_layers("https://github.com/Luisenrique2206/introgeodf-/raw/main/worldMap%20(1).gpkg")
countries=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/worldMap%20(1).gpkg",layer="countryBorders")
rivers=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/worldMap%20(1).gpkg",layer="riverLines")
cities=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/worldMap%20(1).gpkg",layer="cityPoints")
baseLayer=ggplot(data=countries)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=rivers, color='blue') + geom_sf(data=cities, color='red') 
final
```


Grafica_2
```{r}
sf::st_layers("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap%20peru=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg",layer="border")(1).gpkg")
peru=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap%20(1).gpkg",layer="border")
peru_rivers=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap%20(1).gpkg",layer="rivers")
peru_cities=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap%20(1).gpkg",layer="cities")
baseLayer=ggplot(data=peru)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=peru_rivers, color='blue') + geom_sf(data=peru_cities, color='red') 
final
```

Grafica_3
```{r}
sf::st_layers("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg")
peru=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg",layer="border")
peru_rivers=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg",layer="rivers")
peru_cities=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg",layer="cities")
peru_air=read_sf("https://github.com/Luisenrique2206/introgeodf-/raw/main/peruMap_5389.gpkg",layer="airports")
baseLayer=ggplot(data=peru)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=peru_rivers, color='blue')  + geom_sf(data=peru_air, color='black') + geom_sf(data=peru_cities, color='red') +
  coord_sf(datum = st_crs(peru))
final
```